### ISSUE TITLE
[Calendar] Башня

### ISSUE THREAD

**Issue by pavel-b-novikov** [goldenluk/nsudotnet#6]
А вот в той башне Майя для дней недели как-то можно установить зависимость между днем недели и количеством табуляций?

**Comment by goldenluk** [comment]
Можно) Исправил

**Comment by pavel-b-novikov** [comment]
```
for (var day = new DateTime(); day.DayOfWeek != _dateTemp.DayOfWeek; day = day.AddDays(1))
{
    Console.Write("\t");
}
```

Это еще гениальнее башни. Нет, правда. 

Псст, парень. Вообще-то енамы можно кастить к инту

**Comment by goldenluk** [comment]
> Псст, парень. Вообще-то енамы можно кастить к инту

Это и было первой идее к исправлению, но я че-то хрень какую-то сделал, оно не взлетело, я передумал и сделал вот ту штуку которая "гениальнее" башни.

Сделал нормально теперь
